/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAwsRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/azure/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAzureRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/ec2/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEc2Instances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/rds/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRdsInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/rds/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRdsOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/ebs/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEbsTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/azure/mi/purchase-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPurchaseOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/aws/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveAwsPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/aws/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAwsPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/azure/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveAzurePrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/azure/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAzurePrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["calculateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProjectShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                share_id: components["parameters"]["ShareId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeProjectShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-shares/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveProjectShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example 8760
         * @example 0.10
         * @example 12345.67
         */
        Decimal: string;
        /** @enum {string} */
        ResolutionStatus: "fresh" | "cached" | "stale" | "unavailable";
        Session: {
            /** @enum {string} */
            mode: "guest" | "authenticated";
            display_name: string | null;
        };
        Region: {
            code: string;
            label: string;
        };
        RegionCatalog: {
            status: components["schemas"]["ResolutionStatus"];
            /** @constant */
            currency: "USD";
            /** Format: date-time */
            retrieved_at: string | null;
            source_urls: string[];
            warnings: string[];
            items: components["schemas"]["Region"][];
        };
        Ec2Instance: {
            instance_type: string;
            source_vcpu: number;
            memory_gib: components["schemas"]["Decimal"];
        };
        RdsInstance: components["schemas"]["Ec2Instance"];
        RdsOption: {
            /** @enum {string} */
            deployment: "single_az" | "multi_az";
            commercial_term: string;
            storage_class: string;
        };
        EbsType: {
            /** @enum {string} */
            key: "gp3" | "io2" | "ephemeral";
            label: string;
            price_required: boolean;
            pricing_available: boolean;
        };
        Ec2InstanceCatalog: components["schemas"]["CatalogMetadata"] & {
            items: components["schemas"]["Ec2Instance"][];
        };
        RdsInstanceCatalog: components["schemas"]["CatalogMetadata"] & {
            items: components["schemas"]["RdsInstance"][];
        };
        RdsOptionCatalog: components["schemas"]["CatalogMetadata"] & {
            items: components["schemas"]["RdsOption"][];
        };
        EbsTypeCatalog: components["schemas"]["CatalogMetadata"] & {
            items: components["schemas"]["EbsType"][];
        };
        CatalogMetadata: {
            status: components["schemas"]["ResolutionStatus"];
            /** @constant */
            currency: "USD";
            /** Format: date-time */
            retrieved_at: string | null;
            source_urls: string[];
            warnings: string[];
        };
        PurchaseOption: {
            key: components["schemas"]["PurchaseOptionKey"];
            label: string;
            ahb: boolean;
        };
        PurchaseOptionCatalog: {
            status: components["schemas"]["ResolutionStatus"];
            /** @constant */
            currency: "USD";
            /** Format: date-time */
            retrieved_at: string | null;
            source_urls: string[];
            warnings: string[];
            items: components["schemas"]["PurchaseOption"][];
        };
        /** @enum {string} */
        PurchaseOptionKey: "payg" | "ahb" | "one-year" | "ahbone-year" | "three-year" | "ahbthree-year" | "sv-one-year" | "ahbsv-one-year";
        PriceResolutionRequest: {
            /** @constant */
            currency: "USD";
            aws_region?: string | null;
            azure_region: string;
            resources: components["schemas"]["Resource"][];
        };
        PriceResolution: {
            /** @enum {string} */
            provider: "aws" | "azure";
            status: components["schemas"]["ResolutionStatus"];
            snapshot_id: string | null;
            /** Format: date-time */
            retrieved_at?: string | null;
            warnings: string[];
        };
        CalculationRequest: components["schemas"]["EditableProjectFields"] & {
            expected_formula_version?: string | null;
        };
        CalculationRevision: {
            formula_version: string;
            aws_snapshot_id: string | null;
            azure_snapshot_id: string | null;
            resource_results: components["schemas"]["ResourceCalculation"][];
            portfolio_totals: components["schemas"]["PortfolioTotals"];
            warnings: string[];
        };
        ResourceCalculation: {
            /** Format: uuid */
            resource_id: string;
            /** @enum {string|null} */
            mapping_status: "mapped" | "no_mapping" | null;
            aws_pricing_status: components["schemas"]["PricingStatus"];
            azure_pricing_status: components["schemas"]["PricingStatus"];
            target_selection: components["schemas"]["TargetSelection"] | null;
            source_costs: components["schemas"]["SourceCostBreakdown"] | null;
            azure_costs: components["schemas"]["AzureCostBreakdown"] | null;
            savings: components["schemas"]["SavingsBreakdown"] | null;
            explanation_steps: components["schemas"]["ExplanationStep"][];
            unresolved_components: components["schemas"]["UnresolvedComponent"][];
        };
        /** @enum {string} */
        PricingStatus: "fresh" | "cached" | "stale" | "unavailable" | "not_required";
        PortfolioTotals: {
            aws_all_rows_total: components["schemas"]["Decimal"] | null;
            aws_mapped_rows_total: components["schemas"]["Decimal"];
            azure_mapped_rows_total: components["schemas"]["Decimal"];
            required_portfolio_adjustment: components["schemas"]["Decimal"];
            selected_parity_adjustment: components["schemas"]["Decimal"];
            portfolio_after_selected_parity: components["schemas"]["Decimal"];
            portfolio_difference: components["schemas"]["Decimal"];
            comparable_resource_count: number;
            no_mapping_resource_count: number;
            price_unavailable_resource_count: number;
        };
        SourceCostBreakdown: {
            compute_gross: components["schemas"]["Decimal"];
            compute_net: components["schemas"]["Decimal"];
            license_gross: components["schemas"]["Decimal"];
            license_net: components["schemas"]["Decimal"];
            storage_gross: components["schemas"]["Decimal"];
            storage_net: components["schemas"]["Decimal"];
            hardware_annual: components["schemas"]["Decimal"];
            electricity_annual: components["schemas"]["Decimal"];
            total: components["schemas"]["Decimal"];
        };
        AzureCostBreakdown: {
            compute_gross: components["schemas"]["Decimal"];
            additional_ram_gb: components["schemas"]["Decimal"];
            additional_ram_gross: components["schemas"]["Decimal"];
            compute_plus_ram_net: components["schemas"]["Decimal"];
            license_gross: components["schemas"]["Decimal"];
            license_net: components["schemas"]["Decimal"];
            storage_gross: components["schemas"]["Decimal"];
            storage_net: components["schemas"]["Decimal"];
            total_before_parity: components["schemas"]["Decimal"];
        };
        SavingsBreakdown: {
            compute_savings: components["schemas"]["Decimal"];
            license_savings: components["schemas"]["Decimal"];
            storage_savings: components["schemas"]["Decimal"];
            total_savings: components["schemas"]["Decimal"];
            required_adjustment: components["schemas"]["Decimal"];
            selected_adjustment: components["schemas"]["Decimal"];
            azure_after_selected_parity: components["schemas"]["Decimal"];
            difference: components["schemas"]["Decimal"];
        };
        TargetSelection: {
            /** @enum {string} */
            mapping_status: "mapped" | "no_mapping";
            requested_tier: components["schemas"]["ServiceTier"];
            nggp_iops_limit: number;
            selected: components["schemas"]["SelectedTarget"] | null;
            candidates: components["schemas"]["CandidateEvaluation"][];
            outcome_reasons: components["schemas"]["SelectionReason"][];
            storage_escalation: components["schemas"]["StorageEscalation"] | null;
        };
        /** @enum {string} */
        ServiceTier: "next_generation_general_purpose" | "business_critical";
        SelectedTarget: {
            configuration_key: string;
            azure_region: string;
            service_tier: components["schemas"]["ServiceTier"];
            hardware_family: string;
            vcores: number;
            included_memory_gb: components["schemas"]["Decimal"];
            selected_memory_gb: components["schemas"]["Decimal"];
            additional_memory_gb: components["schemas"]["Decimal"];
            storage_architecture: string;
            maximum_storage_gb: components["schemas"]["Decimal"] | null;
        };
        CandidateEvaluation: {
            configuration_key: string;
            vcores: number;
            selected_memory_gb: components["schemas"]["Decimal"] | null;
            eligible: boolean;
            rejection_reasons: components["schemas"]["SelectionReason"][];
        };
        SelectionReason: {
            /** @enum {string} */
            code: "region_unavailable" | "tier_unavailable" | "zone_redundancy_unsupported" | "hardware_family_unsupported" | "insufficient_vcores" | "insufficient_memory" | "insufficient_storage";
            detail: string;
        };
        StorageEscalation: {
            rejected_configuration_key: string;
            rejected_maximum_storage_gb: components["schemas"]["Decimal"];
            selected_configuration_key: string;
        };
        ExplanationStep: {
            code: string;
            message: string;
            values: {
                [key: string]: string;
            };
        };
        UnresolvedComponent: {
            /** @enum {string|null} */
            provider: "aws" | "azure" | null;
            code: string;
            message: string;
        };
        EditableProject: components["schemas"]["EditableProjectFields"];
        ProjectShareCredentials: {
            /** Format: uuid */
            share_id: string;
            /**
             * Format: uuid
             * @description Capability secret. Keep it in the URL fragment and request body only.
             */
            secret: string;
        };
        CreatedProjectShare: components["schemas"]["ProjectShareCredentials"] & {
            /** Format: date-time */
            expires_at: string;
        };
        EditableProjectFields: {
            name: string;
            description?: string | null;
            settings: components["schemas"]["ProjectSettings"];
            resources: components["schemas"]["Resource"][];
            aws_price_snapshot_id: string | null;
            azure_price_snapshot_id: string | null;
        };
        ProjectSettings: {
            /** @enum {string} */
            project_type: "ec2" | "rds" | "on_prem";
            aws_region: string | null;
            azure_region: string;
            /** @constant */
            currency: "USD";
            source_compute_discount: components["schemas"]["Decimal"];
            source_license_discount: components["schemas"]["Decimal"];
            source_storage_discount: components["schemas"]["Decimal"];
            azure_compute_discount: components["schemas"]["Decimal"];
            azure_license_discount: components["schemas"]["Decimal"];
            azure_storage_discount: components["schemas"]["Decimal"];
            selected_parity_adjustment: components["schemas"]["Decimal"];
            default_annual_hours: components["schemas"]["Decimal"];
            default_mi_purchase_option: components["schemas"]["PurchaseOptionKey"];
            enterprise_license_sa_usd_per_two_core_pack?: components["schemas"]["Decimal"] | null;
            standard_license_sa_usd_per_two_core_pack?: components["schemas"]["Decimal"] | null;
            /** @enum {integer|null} */
            remaining_coverage_months?: 12 | 24 | 36 | null;
            electricity_rate_usd_per_kwh?: components["schemas"]["Decimal"] | null;
        };
        Resource: components["schemas"]["Ec2Resource"] | components["schemas"]["RdsResource"] | components["schemas"]["OnPremResource"];
        SharedResourceProperties: {
            /** Format: uuid */
            id: string;
            workload_name: string;
            quantity: number;
            /** @enum {string} */
            sql_edition: "standard" | "enterprise";
            /** @enum {string} */
            license_basis: "license_included" | "byol";
            sql_data_gb_per_instance: components["schemas"]["Decimal"];
            source_ram_gb_per_instance: components["schemas"]["Decimal"];
            annual_hours_per_instance: components["schemas"]["Decimal"];
            mi_purchase_option: components["schemas"]["PurchaseOptionKey"];
        };
        Ec2Resource: components["schemas"]["SharedResourceProperties"] & {
            /** @constant */
            source_type: "ec2";
            instance_type: string;
            volumes: components["schemas"]["EbsVolume"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "Ec2Resource";
        };
        EbsVolume: {
            /** Format: uuid */
            id: string;
            label: string;
            aws_volume_id: string | null;
            /** @enum {string} */
            volume_type: "gp3" | "io2" | "ephemeral";
            capacity_gb: components["schemas"]["Decimal"];
            provisioned_iops: number | null;
            throughput_mibps: components["schemas"]["Decimal"] | null;
        };
        RdsResource: components["schemas"]["SharedResourceProperties"] & {
            /** @constant */
            source_type: "rds";
            instance_type: string;
            /** @enum {string} */
            deployment: "single_az" | "multi_az";
            commercial_term: string;
            storage_class: string;
            source_max_iops: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "RdsResource";
        };
        OnPremResource: components["schemas"]["SharedResourceProperties"] & {
            /** @constant */
            source_type: "on_prem";
            source_vcpu: number;
            licensable_cores: number;
            source_max_iops: number;
            hardware_capex_usd: components["schemas"]["Decimal"];
            depreciation_years: components["schemas"]["Decimal"];
            average_power_kw_override?: components["schemas"]["Decimal"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "OnPremResource";
        };
        Project: components["schemas"]["EditableProjectFields"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            formula_version: string;
            schema_version: string;
            latest_calculation_revision: components["schemas"]["CalculationRevision"] | null;
        };
        ProjectSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            project_type: "ec2" | "rds" | "on_prem";
            /** Format: date-time */
            modified_at: string;
            source_region: string | null;
            azure_region: string;
            resource_count: number;
            source_annual_total: components["schemas"]["Decimal"] | null;
            azure_annual_total: components["schemas"]["Decimal"] | null;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            request_id: string;
            errors?: {
                pointer: string;
                code: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description RFC 9457 Problem Details response. */
        Problem: {
            headers: {
                /** @description Seconds to wait when the request quota is exceeded. */
                "Retry-After"?: string;
                /** @description Current project ETag after a failed precondition. */
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        AwsRegion: string;
        ProjectId: string;
        ShareId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current guest or authenticated principal summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    listAwsRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported AWS source regions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionCatalog"];
                };
            };
        };
    };
    listAzureRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported Azure target regions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionCatalog"];
                };
            };
        };
    };
    listEc2Instances: {
        parameters: {
            query: {
                region: components["parameters"]["AwsRegion"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description EC2 instance metadata available in the latest regional snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ec2InstanceCatalog"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRdsInstances: {
        parameters: {
            query: {
                region: components["parameters"]["AwsRegion"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDS instance metadata available in the latest regional snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RdsInstanceCatalog"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRdsOptions: {
        parameters: {
            query: {
                region: components["parameters"]["AwsRegion"];
                instance_type: string;
                deployment: "single_az" | "multi_az";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commercial and storage options available for the selected RDS shape. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RdsOptionCatalog"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listEbsTypes: {
        parameters: {
            query: {
                region: components["parameters"]["AwsRegion"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description EBS volume types and local pricing availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EbsTypeCatalog"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listPurchaseOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported Azure SQL MI purchase options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOptionCatalog"];
                };
            };
        };
    };
    resolveAwsPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceResolutionRequest"];
            };
        };
        responses: {
            /** @description AWS snapshot status, including normal unavailable outcomes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResolution"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshAwsPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceResolutionRequest"];
            };
        };
        responses: {
            /** @description Forced AWS live-resolution outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResolution"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    resolveAzurePrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceResolutionRequest"];
            };
        };
        responses: {
            /** @description Azure snapshot status, including normal unavailable outcomes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResolution"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshAzurePrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceResolutionRequest"];
            };
        };
        responses: {
            /** @description Forced Azure live-resolution outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResolution"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    calculateProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculationRequest"];
            };
        };
        responses: {
            /** @description Server-owned calculation revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationRevision"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects owned by the current principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditableProject"];
            };
        };
        responses: {
            /** @description Created owner-scoped project. */
            201: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped project. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditableProject"];
            };
        };
        responses: {
            /** @description Updated owner-scoped project. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted immediately. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    createProjectShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A reusable project-share credential that expires after 30 days. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedProjectShare"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeProjectShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                share_id: components["parameters"]["ShareId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project share revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    resolveProjectShare: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectShareCredentials"];
            };
        };
        responses: {
            /** @description Editable project snapshot with no source ownership metadata or revision. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditableProject"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
