/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privacy-consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["savePrivacyConsent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/help": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a question from the reviewed application-help catalog. */
        post: operations["getAssistantHelp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run one bounded tool-enabled assistant turn for the signed-in owner. */
        post: operations["runAssistantTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Normalize one JPEG or PNG and return a validated project proposal. */
        post: operations["analyzeAssistantImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply one explicitly confirmed project patch through the normal project service. */
        post: operations["executeAssistantAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAwsRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/azure/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAzureRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/ec2/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEc2Instances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/rds/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRdsInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/rds/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRdsOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/aws/ebs/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEbsTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/azure/mi/purchase-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPurchaseOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/aws/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveAwsPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/aws/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAwsPrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/azure/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveAzurePrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pricing/azure/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAzurePrices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["calculateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProjectShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/calculator-launches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCalculatorLaunch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculator-launches/{launch_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launch_id: components["parameters"]["LaunchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimCalculatorLaunch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculator-launches/{launch_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launch_id: components["parameters"]["LaunchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acknowledgeCalculatorLaunch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                share_id: components["parameters"]["ShareId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeProjectShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-shares/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveProjectShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example 8760
         * @example 0.10
         * @example 12345.67
         */
        Decimal: string;
        /** @enum {string} */
        ResolutionStatus: "fresh" | "cached" | "stale" | "unavailable";
        Session: {
            /** @enum {string} */
            mode: "guest" | "authenticated";
            display_name: string | null;
            /**
             * Format: email
             * @description Optional email-like value supplied by the identity provider for contact-form prefill only.
             */
            email_address: string | null;
            privacy_consent: components["schemas"]["PrivacyConsentStatus"];
        };
        PrivacyConsentStatus: {
            notice_version: string;
            required: boolean;
            /** Format: date-time */
            accepted_at: string | null;
            allow_contact: boolean;
            /**
             * Format: email
             * @description Stored only when Azure SQL contact permission is enabled.
             */
            email_address: string | null;
        };
        SavePrivacyConsentRequest: {
            notice_version: string;
            /** @constant */
            accepted: true;
            allow_contact: boolean;
            /** Format: email */
            email_address: string | null;
        };
        AssistantHelpRequest: {
            question: string;
        };
        AssistantHelpResponse: {
            answer: string;
            references: components["schemas"]["AssistantHelpReference"][];
        };
        AssistantHelpReference: {
            control_id: string;
            label: string;
        };
        AssistantTurnRequest: {
            question: string;
            /**
             * Format: uuid
             * @description Optional owner-scoped saved project selected by the host for this turn.
             */
            project_id: string | null;
        };
        AssistantTurnResponse: {
            answer: string;
            references: components["schemas"]["AssistantHelpReference"][];
            proposal: components["schemas"]["AssistantProposal"] | null;
        };
        /** @enum {string} */
        AssistantAction: "apply_project_patch";
        AssistantProjectPatch: {
            name?: string;
            description?: string | null;
            settings?: components["schemas"]["ProjectSettings"];
            resources?: components["schemas"]["Resource"][];
        };
        AssistantProjectPatchChange: {
            pointer: string;
            before: unknown;
            after: unknown;
        };
        AssistantProjectPatchProposal: {
            /** @description Correlation fingerprint for detecting accidental request drift; it is not authorization or proof of confirmation. */
            proposal_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "apply_project_patch";
            /** Format: uuid */
            project_id: string;
            expected_etag: string;
            patch: components["schemas"]["AssistantProjectPatch"];
            changes: components["schemas"]["AssistantProjectPatchChange"][];
        };
        AssistantNewProjectDraftProposal: {
            /** @description Correlation fingerprint for detecting accidental response drift; it is not authorization or proof of persistence. */
            proposal_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "open_project_draft";
            project: components["schemas"]["EditableProject"];
        };
        AssistantProposal: components["schemas"]["AssistantProjectPatchProposal"] | components["schemas"]["AssistantNewProjectDraftProposal"];
        AssistantImageProjectClassification: {
            /** @enum {string} */
            project_type: "ec2" | "ec2_vm" | "rds" | "on_prem" | "sql_payg" | "unknown";
            /** @enum {string} */
            confidence: "high" | "medium" | "low";
            evidence: string[];
            ambiguities: string[];
        };
        AssistantImageResponse: {
            answer: string;
            classification: components["schemas"]["AssistantImageProjectClassification"] | null;
            proposal: components["schemas"]["AssistantProposal"] | null;
            omissions: string[];
            uncertainties: string[];
        };
        AssistantActionRequest: {
            proposal_id: string;
            action: components["schemas"]["AssistantAction"];
            /** Format: uuid */
            project_id: string;
            expected_etag: string;
            patch: components["schemas"]["AssistantProjectPatch"];
        };
        Region: {
            code: string;
            label: string;
        };
        RegionCatalog: {
            status: components["schemas"]["ResolutionStatus"];
            /** @constant */
            currency: "USD";
            /** Format: date-time */
            retrieved_at: string | null;
            source_urls: string[];
            warnings: string[];
            items: components["schemas"]["Region"][];
        };
        Ec2Instance: {
            instance_type: string;
            source_vcpu: number;
            memory_gib: components["schemas"]["Decimal"];
        };
        RdsInstance: components["schemas"]["Ec2Instance"];
        RdsOption: {
            /** @enum {string} */
            deployment: "single_az" | "multi_az";
            commercial_term: string;
            storage_class: string;
        };
        EbsType: {
            /** @enum {string} */
            key: "gp3" | "io2" | "ephemeral";
            label: string;
            price_required: boolean;
            pricing_available: boolean;
        };
        Ec2InstanceCatalog: components["schemas"]["CatalogMetadata"] & {
            items: components["schemas"]["Ec2Instance"][];
        };
        RdsInstanceCatalog: components["schemas"]["CatalogMetadata"] & {
            items: components["schemas"]["RdsInstance"][];
        };
        RdsOptionCatalog: components["schemas"]["CatalogMetadata"] & {
            items: components["schemas"]["RdsOption"][];
        };
        EbsTypeCatalog: components["schemas"]["CatalogMetadata"] & {
            items: components["schemas"]["EbsType"][];
        };
        CatalogMetadata: {
            status: components["schemas"]["ResolutionStatus"];
            /** @constant */
            currency: "USD";
            /** Format: date-time */
            retrieved_at: string | null;
            source_urls: string[];
            warnings: string[];
        };
        PurchaseOption: {
            key: components["schemas"]["PurchaseOptionKey"];
            label: string;
            ahb: boolean;
        };
        PurchaseOptionCatalog: {
            status: components["schemas"]["ResolutionStatus"];
            /** @constant */
            currency: "USD";
            /** Format: date-time */
            retrieved_at: string | null;
            source_urls: string[];
            warnings: string[];
            items: components["schemas"]["PurchaseOption"][];
        };
        /** @enum {string} */
        PurchaseOptionKey: "payg" | "ahb" | "one-year" | "ahbone-year" | "three-year" | "ahbthree-year" | "sv-one-year" | "ahbsv-one-year";
        PriceResolutionRequest: {
            /** @constant */
            currency: "USD";
            aws_region?: string | null;
            azure_region: string;
            resources: components["schemas"]["Resource"][];
        };
        PriceResolution: {
            /** @enum {string} */
            provider: "aws" | "azure";
            status: components["schemas"]["ResolutionStatus"];
            snapshot_id: string | null;
            /** Format: date-time */
            retrieved_at?: string | null;
            warnings: string[];
        };
        CalculationRequest: components["schemas"]["EditableProjectFields"] & {
            expected_formula_version?: string | null;
        };
        CalculationRevision: {
            formula_version: string;
            aws_snapshot_id: string | null;
            azure_snapshot_id: string | null;
            resource_results: components["schemas"]["ResourceCalculation"][];
            portfolio_totals: components["schemas"]["PortfolioTotals"];
            warnings: string[];
            sql_payg_analysis?: components["schemas"]["SqlPaygAnalysis"];
        };
        SqlPaygAnalysis: {
            enterprise_licensed_cores: number;
            standard_licensed_cores: number;
            software_assurance_annual_usd: components["schemas"]["Decimal"];
            annual_hours: components["schemas"]["Decimal"];
            enterprise_payg_usd_per_core_hour: components["schemas"]["Decimal"];
            standard_payg_usd_per_core_hour: components["schemas"]["Decimal"];
            payg_gross_annual_usd: components["schemas"]["Decimal"];
            required_payg_discount: components["schemas"]["Decimal"];
            payg_at_breakeven_usd: components["schemas"]["Decimal"];
            applied_payg_discount: components["schemas"]["Decimal"];
            payg_net_annual_usd: components["schemas"]["Decimal"];
            annual_savings_usd: components["schemas"]["Decimal"];
            /** @enum {string} */
            outcome: "no_discount_needed" | "discount_required" | "full_discount_required";
            /** Format: uri */
            rate_source_url: string;
            /** Format: date */
            rate_verified_on: string;
        } | null;
        ResourceCalculation: {
            /** Format: uuid */
            resource_id: string;
            storage_inputs: components["schemas"]["StorageInputs"];
            /** @enum {string|null} */
            mapping_status: "mapped" | "no_mapping" | null;
            aws_pricing_status: components["schemas"]["PricingStatus"];
            azure_pricing_status: components["schemas"]["PricingStatus"];
            target_selection: components["schemas"]["TargetSelection"] | null;
            vm_target_selection: components["schemas"]["VmTargetSelection"] | null;
            source_costs: components["schemas"]["SourceCostBreakdown"] | null;
            azure_costs: components["schemas"]["AzureCostBreakdown"] | null;
            purchase_option_discounts: components["schemas"]["PurchaseOptionDiscounts"] | null;
            savings: components["schemas"]["SavingsBreakdown"] | null;
            explanation_steps: components["schemas"]["ExplanationStep"][];
            unresolved_components: components["schemas"]["UnresolvedComponent"][];
        };
        StorageInputs: {
            sql_data_gb_per_instance: components["schemas"]["Decimal"];
            persistent_ebs_gb_per_instance: components["schemas"]["Decimal"];
            azure_storage_gb_per_instance: components["schemas"]["Decimal"];
        };
        /** @enum {string} */
        PricingStatus: "fresh" | "cached" | "stale" | "unavailable" | "not_required";
        PortfolioTotals: {
            aws_all_rows_total: components["schemas"]["Decimal"] | null;
            aws_mapped_rows_total: components["schemas"]["Decimal"];
            azure_mapped_rows_total: components["schemas"]["Decimal"];
            required_portfolio_adjustment: components["schemas"]["Decimal"];
            selected_parity_adjustment: components["schemas"]["Decimal"];
            portfolio_after_selected_parity: components["schemas"]["Decimal"];
            portfolio_difference: components["schemas"]["Decimal"];
            comparable_resource_count: number;
            no_mapping_resource_count: number;
            price_unavailable_resource_count: number;
        };
        SourceCostBreakdown: {
            compute_gross: components["schemas"]["Decimal"];
            compute_net: components["schemas"]["Decimal"];
            license_gross: components["schemas"]["Decimal"];
            license_net: components["schemas"]["Decimal"];
            storage_gross: components["schemas"]["Decimal"];
            storage_net: components["schemas"]["Decimal"];
            hardware_annual: components["schemas"]["Decimal"];
            electricity_annual: components["schemas"]["Decimal"];
            total: components["schemas"]["Decimal"];
        };
        AzureCostBreakdown: {
            compute_gross: components["schemas"]["Decimal"];
            additional_ram_gb: components["schemas"]["Decimal"];
            additional_ram_gross: components["schemas"]["Decimal"];
            compute_plus_ram_net: components["schemas"]["Decimal"];
            license_gross: components["schemas"]["Decimal"];
            license_net: components["schemas"]["Decimal"];
            storage_gross: components["schemas"]["Decimal"];
            storage_net: components["schemas"]["Decimal"];
            total_before_parity: components["schemas"]["Decimal"];
        };
        PurchaseOptionDiscounts: {
            payg: components["schemas"]["Decimal"];
            one_year_reserved: components["schemas"]["Decimal"];
            three_year_reserved: components["schemas"]["Decimal"];
            one_year_savings_plan: components["schemas"]["Decimal"];
            azure_hybrid_benefit: components["schemas"]["Decimal"];
        };
        SavingsBreakdown: {
            compute_savings: components["schemas"]["Decimal"];
            license_savings: components["schemas"]["Decimal"];
            storage_savings: components["schemas"]["Decimal"];
            total_savings: components["schemas"]["Decimal"];
            required_adjustment: components["schemas"]["Decimal"];
            selected_adjustment: components["schemas"]["Decimal"];
            azure_after_selected_parity: components["schemas"]["Decimal"];
            difference: components["schemas"]["Decimal"];
        };
        TargetSelection: {
            /** @enum {string} */
            mapping_status: "mapped" | "no_mapping";
            requested_tier: components["schemas"]["ServiceTier"];
            nggp_iops_limit: number;
            selected: components["schemas"]["SelectedTarget"] | null;
            candidates: components["schemas"]["CandidateEvaluation"][];
            outcome_reasons: components["schemas"]["SelectionReason"][];
            storage_escalation: components["schemas"]["StorageEscalation"] | null;
        };
        VmTargetSelection: {
            /** @enum {string} */
            mapping_status: "mapped" | "no_mapping";
            recommendation_status: components["schemas"]["VmRecommendationStatus"];
            requested_lineage: components["schemas"]["VmLineage"];
            selected: components["schemas"]["SelectedVmTarget"] | null;
            candidates: components["schemas"]["VmCandidateEvaluation"][];
            outcome_reasons: components["schemas"]["VmSelectionReason"][];
        };
        /** @enum {string} */
        VmLineage: "burstable" | "general_purpose" | "memory_optimized";
        /** @enum {string} */
        VmRecommendationStatus: "recommended" | "capacity_fit_review_required" | "incomplete" | "no_eligible_target";
        /** @enum {string} */
        VmLifecycle: "current" | "previous";
        SelectedVmTarget: {
            arm_sku_name: string;
            display_family: string;
            lineage: components["schemas"]["VmLineage"];
            generation: string;
            generation_rank: number;
            lifecycle: components["schemas"]["VmLifecycle"];
            azure_region: string;
            vcpus: number;
            memory_gb: components["schemas"]["Decimal"];
            max_data_disk_count: number;
            uncached_disk_iops: number;
            uncached_disk_throughput_mbps: number;
            local_temp_disk_gb: components["schemas"]["Decimal"] | null;
            disks: components["schemas"]["SelectedManagedDisk"][];
        };
        SelectedManagedDisk: {
            /** Format: uuid */
            volume_id: string;
            label: string;
            role: components["schemas"]["VmDiskRole"];
            offer_key: string;
            display_name: string;
            tier_key: string | null;
            capacity_gb: components["schemas"]["Decimal"];
            provisioned_iops: number;
            provisioned_throughput_mbps: components["schemas"]["Decimal"];
            billed_additional_iops: number;
            billed_additional_throughput_mbps: components["schemas"]["Decimal"];
        };
        VmCandidateEvaluation: {
            arm_sku_name: string;
            vcpus: number;
            memory_gb: components["schemas"]["Decimal"];
            eligible: boolean;
            rejection_reasons: components["schemas"]["VmSelectionReason"][];
        };
        VmSelectionReason: {
            /** @enum {string} */
            code: "region_unavailable" | "lineage_mismatch" | "lifecycle_ineligible" | "windows_unsupported" | "architecture_unsupported" | "premium_io_unsupported" | "insufficient_vcpu" | "insufficient_memory" | "insufficient_local_temp_disk" | "data_disk_count_exceeded" | "no_eligible_disk_offer" | "aggregate_disk_iops_exceeded" | "aggregate_disk_throughput_exceeded" | "target_override_ineligible" | "burst_policy_review_required" | "instance_store_review_required" | "ephemeral_data_loss_incompatible" | "high_frequency_review_required" | "volume_role_unconfirmed" | "price_unavailable";
            detail: string;
        };
        /** @enum {string} */
        ServiceTier: "next_generation_general_purpose" | "business_critical";
        SelectedTarget: {
            configuration_key: string;
            azure_region: string;
            service_tier: components["schemas"]["ServiceTier"];
            hardware_family: string;
            vcores: number;
            zone_redundant: boolean;
            included_memory_gb: components["schemas"]["Decimal"];
            selected_memory_gb: components["schemas"]["Decimal"];
            additional_memory_gb: components["schemas"]["Decimal"];
            storage_architecture: string;
            maximum_storage_gb: components["schemas"]["Decimal"] | null;
        };
        CandidateEvaluation: {
            configuration_key: string;
            vcores: number;
            selected_memory_gb: components["schemas"]["Decimal"] | null;
            eligible: boolean;
            rejection_reasons: components["schemas"]["SelectionReason"][];
        };
        SelectionReason: {
            /** @enum {string} */
            code: "region_unavailable" | "tier_unavailable" | "zone_redundancy_unsupported" | "hardware_family_unsupported" | "insufficient_vcores" | "insufficient_memory" | "insufficient_storage";
            detail: string;
        };
        StorageEscalation: {
            rejected_configuration_key: string;
            rejected_maximum_storage_gb: components["schemas"]["Decimal"];
            selected_configuration_key: string;
        };
        ExplanationStep: {
            code: string;
            message: string;
            values: {
                [key: string]: string;
            };
        };
        UnresolvedComponent: {
            /** @enum {string|null} */
            provider: "aws" | "azure" | null;
            code: string;
            message: string;
        };
        EditableProject: components["schemas"]["EditableProjectFields"];
        ProjectShareCredentials: {
            /** Format: uuid */
            share_id: string;
            /**
             * Format: uuid
             * @description Capability secret. Keep it in the URL fragment and request body only.
             */
            secret: string;
        };
        CreatedProjectShare: components["schemas"]["ProjectShareCredentials"] & {
            /** Format: date-time */
            expires_at: string;
        };
        CreateCalculatorLaunchRequest: {
            /** Format: uuid */
            launch_id: string;
            /** @constant */
            protocol_version: 1;
        };
        CalculatorLaunch: {
            /** Format: uuid */
            launch_id: string;
            /** @constant */
            status: "ready";
            /** Format: date-time */
            claim_expires_at: string;
            minimum_companion_version: string;
            /** @constant */
            protocol_version: 1;
        };
        ClaimCalculatorLaunchRequest: {
            /** Format: uuid */
            companion_instance_id: string;
            companion_version: string;
            supported_protocol_versions: number[];
            supported_manifest_versions: number[];
            supported_calculator_contracts: string[];
        };
        ClaimedCalculatorLaunch: {
            manifest_sha256: string;
            manifest: components["schemas"]["CalculatorManifest"];
        };
        AcknowledgeCalculatorLaunchRequest: {
            /** Format: uuid */
            companion_instance_id: string;
        };
        CalculatorManifest: {
            /** @constant */
            schema_version: 2;
            /** @constant */
            calculator_contract_version: "2026-08-24";
            /**
             * Format: uri
             * @constant
             */
            calculator_url: "https://azure.microsoft.com/en-us/pricing/calculator/";
            /** Format: date-time */
            generated_at: string;
            /** @constant */
            currency: "USD";
            /** @constant */
            locale: "en-US";
            estimate_name: string;
            items: components["schemas"]["CalculatorManifestItem"][];
        };
        CalculatorManifestItem: {
            item_key: string;
            display_name: string;
            /** @constant */
            product: "azure_sql_managed_instance";
            region: string;
            /** @constant */
            deployment_model: "single_instance";
            /** @enum {string} */
            service_tier: "next_generation_general_purpose" | "business_critical";
            /** @enum {string} */
            hardware_family: "premium_series" | "premium_series_memory_optimized";
            vcores: number;
            selected_memory_gb: components["schemas"]["Decimal"];
            zone_redundant: boolean;
            quantity: number;
            hours_per_month: components["schemas"]["Decimal"];
            /** @enum {string} */
            purchase_option: "payg" | "one_year_reservation" | "three_year_reservation" | "one_year_savings_plan";
            azure_hybrid_benefit: boolean;
            data_storage_gb: components["schemas"]["Decimal"];
            backup_storage_gb: components["schemas"]["Decimal"];
            expected_public_annual: components["schemas"]["CalculatorExpectedPublicAnnual"];
        };
        CalculatorExpectedPublicAnnual: {
            compute: components["schemas"]["Decimal"];
            additional_memory: components["schemas"]["Decimal"];
            license: components["schemas"]["Decimal"];
            storage: components["schemas"]["Decimal"];
            total_before_parity: components["schemas"]["Decimal"];
        };
        EditableProjectFields: {
            name: string;
            description?: string | null;
            settings: components["schemas"]["ProjectSettings"];
            resources: components["schemas"]["Resource"][];
            aws_price_snapshot_id: string | null;
            azure_price_snapshot_id: string | null;
        };
        ProjectSettings: {
            /** @enum {string} */
            project_type: "ec2" | "ec2_vm" | "rds" | "on_prem" | "sql_payg";
            aws_region: string | null;
            azure_region: string;
            /** @constant */
            currency: "USD";
            source_compute_discount: components["schemas"]["Decimal"];
            source_license_discount: components["schemas"]["Decimal"];
            source_storage_discount: components["schemas"]["Decimal"];
            azure_compute_discount: components["schemas"]["Decimal"];
            azure_license_discount: components["schemas"]["Decimal"];
            azure_storage_discount: components["schemas"]["Decimal"];
            /** @description Applied PAYG discount for SQL Pay As You Go projects; selected portfolio adjustment otherwise. */
            selected_parity_adjustment: components["schemas"]["Decimal"];
            /** @description Authoritative annual utilization for SQL Pay As You Go projects; default resource hours otherwise. */
            default_annual_hours: components["schemas"]["Decimal"];
            default_mi_purchase_option: components["schemas"]["PurchaseOptionKey"];
            enterprise_license_sa_usd_per_two_core_pack?: components["schemas"]["Decimal"] | null;
            standard_license_sa_usd_per_two_core_pack?: components["schemas"]["Decimal"] | null;
            /** @enum {integer|null} */
            remaining_coverage_months?: 12 | 24 | 36 | null;
            electricity_rate_usd_per_kwh?: components["schemas"]["Decimal"] | null;
            sql_payg?: components["schemas"]["SqlPaygSettings"] | null;
        };
        SqlPaygSettings: {
            enterprise_licensed_cores: number;
            standard_licensed_cores: number;
            software_assurance_annual_usd: components["schemas"]["Decimal"];
        };
        Resource: components["schemas"]["Ec2Resource"] | components["schemas"]["Ec2VmResource"] | components["schemas"]["RdsResource"] | components["schemas"]["OnPremResource"];
        SharedResourceProperties: {
            /** Format: uuid */
            id: string;
            workload_name: string;
            server_name: string | null;
            quantity: number;
            /** @enum {string} */
            sql_edition: "standard" | "enterprise";
            /** @enum {string} */
            license_basis: "license_included" | "byol";
            sql_data_gb_per_instance: components["schemas"]["Decimal"];
            source_ram_gb_per_instance: components["schemas"]["Decimal"];
            annual_hours_per_instance: components["schemas"]["Decimal"];
            mi_purchase_option: components["schemas"]["PurchaseOptionKey"];
        };
        Ec2Resource: components["schemas"]["SharedResourceProperties"] & {
            /** @constant */
            source_type: "ec2";
            instance_type: string;
            volumes: components["schemas"]["EbsVolume"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "ec2";
        };
        SharedVmResourceProperties: {
            /** Format: uuid */
            id: string;
            workload_name: string;
            server_name: string | null;
            quantity: number;
            source_ram_gb_per_instance: components["schemas"]["Decimal"];
            annual_hours_per_instance: components["schemas"]["Decimal"];
        };
        Ec2VmResource: components["schemas"]["SharedVmResourceProperties"] & {
            /** @constant */
            source_type: "ec2_vm";
            instance_type: string;
            requirements: components["schemas"]["Ec2VmRequirements"];
            volumes: components["schemas"]["VmVolume"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "ec2_vm";
        };
        Ec2VmRequirements: {
            burst_policy: components["schemas"]["VmBurstPolicy"];
            instance_store_use: components["schemas"]["VmInstanceStoreUse"];
            required_local_temp_disk_gb: components["schemas"]["Decimal"] | null;
            ephemeral_data_loss_acceptable: boolean | null;
            high_frequency_requirement: components["schemas"]["VmHighFrequencyRequirement"];
            requested_target_arm_sku: string | null;
        };
        /** @enum {string} */
        VmBurstPolicy: "confirmed_burst_compatible" | "requires_sustained_cpu" | "unknown" | "not_applicable";
        /** @enum {string} */
        VmInstanceStoreUse: "unknown" | "not_used" | "used";
        /** @enum {string} */
        VmHighFrequencyRequirement: "required" | "unknown" | "capacity_fit_accepted" | "not_applicable";
        /** @enum {string} */
        VmDiskRole: "os" | "data" | "unknown";
        VmVolume: {
            /** Format: uuid */
            id: string;
            label: string;
            aws_volume_id: string | null;
            /** @enum {string} */
            volume_type: "gp3" | "io2";
            role: components["schemas"]["VmDiskRole"];
            capacity_gb: components["schemas"]["Decimal"];
            provisioned_iops: number;
            throughput_mibps: components["schemas"]["Decimal"] | null;
        };
        EbsVolume: {
            /** Format: uuid */
            id: string;
            label: string;
            aws_volume_id: string | null;
            /** @enum {string} */
            volume_type: "gp3" | "io2" | "ephemeral";
            capacity_gb: components["schemas"]["Decimal"];
            provisioned_iops: number | null;
            throughput_mibps: components["schemas"]["Decimal"] | null;
        };
        RdsResource: components["schemas"]["SharedResourceProperties"] & {
            /** @constant */
            source_type: "rds";
            instance_type: string;
            /** @enum {string} */
            deployment: "single_az" | "multi_az";
            commercial_term: string;
            storage_class: string;
            source_max_iops: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "rds";
        };
        OnPremResource: components["schemas"]["SharedResourceProperties"] & {
            /** @constant */
            source_type: "on_prem";
            source_vcpu: number;
            licensable_cores: number;
            source_max_iops: number;
            hardware_capex_usd: components["schemas"]["Decimal"];
            depreciation_years: components["schemas"]["Decimal"];
            average_power_kw_override?: components["schemas"]["Decimal"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "on_prem";
        };
        Project: components["schemas"]["EditableProjectFields"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            formula_version: string;
            schema_version: string;
            latest_calculation_revision: components["schemas"]["CalculationRevision"] | null;
        };
        ProjectSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            project_type: "ec2" | "ec2_vm" | "rds" | "on_prem" | "sql_payg";
            /** Format: date-time */
            modified_at: string;
            source_region: string | null;
            azure_region: string;
            resource_count: number;
            source_annual_total: components["schemas"]["Decimal"] | null;
            azure_annual_total: components["schemas"]["Decimal"] | null;
            azure_savings: components["schemas"]["Decimal"] | null;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            request_id: string;
            errors?: {
                pointer: string;
                code: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description RFC 9457 Problem Details response. */
        Problem: {
            headers: {
                "Cache-Control"?: "no-store";
                /** @description Seconds to wait when the request quota is exceeded. */
                "Retry-After"?: string;
                /** @description Current project ETag after a failed precondition. */
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        AwsRegion: string;
        ProjectId: string;
        ShareId: string;
        LaunchId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current guest or authenticated principal summary. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    savePrivacyConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePrivacyConsentRequest"];
            };
        };
        responses: {
            /** @description Current owner-scoped privacy acceptance and contact preference. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyConsentStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAssistantHelp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantHelpRequest"];
            };
        };
        responses: {
            /** @description Deterministic application help with matched control references. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantHelpResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    runAssistantTurn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantTurnRequest"];
            };
        };
        responses: {
            /** @description Plain-text assistant answer grounded in allowlisted application tools. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantTurnResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    analyzeAssistantImage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional owner-scoped saved project selected by the host. When absent, the agent may stage a new unsaved browser draft. */
                "x-tco-project-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
            };
        };
        responses: {
            /** @description A request-scoped, validated patch or new browser-draft proposal. No image or project is saved. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantImageResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    executeAssistantAction: {
        parameters: {
            query?: never;
            header: {
                /** @description Dedicated same-origin browser confirmation, separate from natural-language intent. */
                "x-tco-action-confirmation": "apply_project_patch";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantActionRequest"];
            };
        };
        responses: {
            /** @description Authoritative owner-scoped project after the atomic update and verification read. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAwsRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported AWS source regions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionCatalog"];
                };
            };
        };
    };
    listAzureRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported Azure target regions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionCatalog"];
                };
            };
        };
    };
    listEc2Instances: {
        parameters: {
            query: {
                region: components["parameters"]["AwsRegion"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description EC2 instance metadata available in the latest regional snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ec2InstanceCatalog"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRdsInstances: {
        parameters: {
            query: {
                region: components["parameters"]["AwsRegion"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDS instance metadata available in the latest regional snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RdsInstanceCatalog"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRdsOptions: {
        parameters: {
            query: {
                region: components["parameters"]["AwsRegion"];
                instance_type: string;
                deployment: "single_az" | "multi_az";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commercial and storage options available for the selected RDS shape. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RdsOptionCatalog"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listEbsTypes: {
        parameters: {
            query: {
                region: components["parameters"]["AwsRegion"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description EBS volume types and local pricing availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EbsTypeCatalog"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listPurchaseOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported Azure SQL MI purchase options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOptionCatalog"];
                };
            };
        };
    };
    resolveAwsPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceResolutionRequest"];
            };
        };
        responses: {
            /** @description AWS snapshot status, including normal unavailable outcomes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResolution"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshAwsPrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceResolutionRequest"];
            };
        };
        responses: {
            /** @description Forced AWS live-resolution outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResolution"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    resolveAzurePrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceResolutionRequest"];
            };
        };
        responses: {
            /** @description Azure snapshot status, including normal unavailable outcomes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResolution"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refreshAzurePrices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceResolutionRequest"];
            };
        };
        responses: {
            /** @description Forced Azure live-resolution outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResolution"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    calculateProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculationRequest"];
            };
        };
        responses: {
            /** @description Server-owned calculation revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationRevision"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects owned by the current principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditableProject"];
            };
        };
        responses: {
            /** @description Created owner-scoped project. */
            201: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped project. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditableProject"];
            };
        };
        responses: {
            /** @description Updated owner-scoped project. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted immediately. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    createProjectShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A reusable project-share credential that expires after 30 days. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedProjectShare"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCalculatorLaunch: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCalculatorLaunchRequest"];
            };
        };
        responses: {
            /** @description Existing idempotent launch bound to the same project revision. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorLaunch"];
                };
            };
            /** @description One-time owner-scoped Calculator launch created. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorLaunch"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    claimCalculatorLaunch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                launch_id: components["parameters"]["LaunchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimCalculatorLaunchRequest"];
            };
        };
        responses: {
            /** @description Immutable manifest claimed by the authorized companion instance. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimedCalculatorLaunch"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    acknowledgeCalculatorLaunch: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                launch_id: components["parameters"]["LaunchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeCalculatorLaunchRequest"];
            };
        };
        responses: {
            /** @description Manifest receipt acknowledged and manifest payload purged. */
            204: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeProjectShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                share_id: components["parameters"]["ShareId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project share revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    resolveProjectShare: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectShareCredentials"];
            };
        };
        responses: {
            /** @description Editable project snapshot with no source ownership metadata or revision. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditableProject"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
