//! Azure Virtual Machine and managed-disk target selection for the `ec2_vm` workload.
//!
//! This module owns the capability catalogs, the source-class policy, and the deterministic
//! selection algorithm described in sections 7 and 8 of `docs/EC2-VM-TCO-SPEC.md`. Capability
//! filters run before a bounded pricing view from the same calculation snapshot verifies complete
//! rates and supplies the final price tie-breaker.

use std::{
    cmp::Ordering,
    collections::{BTreeMap, BTreeSet},
};

use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use crate::domain::{decimal::DecimalValue, resource::VmDiskRole};

use super::target_selector::MappingStatus;

/// Reviewed Azure Virtual Machine capability catalog. Generated by
/// `research/Generate-AzureVmCapabilityCatalog.ps1`.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct VmCapabilityCatalog {
    pub schema_version: String,
    pub candidates: Vec<VmSizeCandidate>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct VmSizeCandidate {
    pub arm_sku_name: String,
    pub display_family: String,
    pub lineage: VmLineage,
    pub generation: String,
    /// Reviewed rank within the lineage. Higher is newer. Never parsed from the SKU name.
    pub generation_rank: u32,
    pub lifecycle: VmLifecycle,
    pub azure_region: String,
    pub cpu_architecture: String,
    pub windows_eligible: bool,
    pub vcpus: u32,
    pub memory_gb: DecimalValue,
    pub max_data_disk_count: u32,
    pub premium_io: bool,
    pub uncached_disk_iops: u64,
    pub uncached_disk_throughput_mbps: u64,
    /// Documented usable local temporary disk. `None` means the reviewed family has no local disk.
    pub local_temp_disk_gb: Option<DecimalValue>,
    pub source_url: String,
    pub documentation_url: String,
    pub reviewed_date: String,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum VmLineage {
    Burstable,
    GeneralPurpose,
    MemoryOptimized,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum VmLifecycle {
    Current,
    Previous,
}

/// Reviewed Azure managed-disk capability catalog.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ManagedDiskCatalog {
    pub schema_version: String,
    pub offers: Vec<ManagedDiskOffer>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ManagedDiskOffer {
    pub offer_key: String,
    pub display_name: String,
    pub redundancy: String,
    pub allowed_roles: Vec<VmDiskRole>,
    /// True when capacity, IOPS, and throughput are provisioned independently, as on Premium SSD v2.
    pub performance_is_provisioned_independently: bool,
    pub azure_regions: Vec<String>,
    pub included_iops: Option<u64>,
    pub included_throughput_mbps: Option<DecimalValue>,
    pub maximum_iops: u64,
    pub maximum_throughput_mbps: u64,
    pub capacity_increment_gb: Option<DecimalValue>,
    pub minimum_capacity_gb: Option<DecimalValue>,
    pub maximum_capacity_gb: DecimalValue,
    pub tiers: Vec<ManagedDiskTier>,
    pub source_url: String,
    pub reviewed_date: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ManagedDiskTier {
    pub tier_key: String,
    pub capacity_gb: DecimalValue,
    pub provisioned_iops: u64,
    pub provisioned_throughput_mbps: DecimalValue,
}

/// Semantic class of the source EC2 instance family. Derived from the reviewed policy below, not
/// from an ad hoc string test scattered through the calculation code.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceClass {
    Burstable,
    GeneralPurpose,
    MemoryOptimized,
    HighFrequencyMemoryOptimized,
}

impl SourceClass {
    /// Preferred Azure lineage for this source class, per section 8.3.
    pub fn target_lineage(self) -> VmLineage {
        match self {
            Self::Burstable => VmLineage::Burstable,
            Self::GeneralPurpose => VmLineage::GeneralPurpose,
            Self::MemoryOptimized | Self::HighFrequencyMemoryOptimized => {
                VmLineage::MemoryOptimized
            }
        }
    }

    /// Caveat that must remain visible in the result whenever this class is mapped.
    pub fn required_caveat(self) -> Option<&'static str> {
        match self {
            Self::Burstable => Some(
                "The source is burstable and maps to the Azure burstable lineage. AWS and Azure CPU-credit models are not claimed to be identical.",
            ),
            Self::HighFrequencyMemoryOptimized => Some(
                "The source is a high-frequency instance. This target is a capacity fit on vCPU and memory only; per-core performance equivalence is not claimed and requires review outside this estimate.",
            ),
            Self::GeneralPurpose | Self::MemoryOptimized => None,
        }
    }
}

/// Reviewed AWS instance-family policy. An unlisted family has no recommended mapping rather than
/// a guessed one.
pub fn classify_source_instance(instance_type: &str) -> Option<SourceClass> {
    let family = instance_type
        .split('.')
        .next()?
        .trim()
        .to_ascii_lowercase()
        .chars()
        .take_while(|character| character.is_ascii_alphabetic())
        .collect::<String>();

    match family.as_str() {
        "t" => Some(SourceClass::Burstable),
        "m" => Some(SourceClass::GeneralPurpose),
        "r" => Some(SourceClass::MemoryOptimized),
        "z" => Some(SourceClass::HighFrequencyMemoryOptimized),
        _ => None,
    }
}

/// One persistent source volume that must survive as its own target managed disk.
#[derive(Clone, Debug, PartialEq)]
pub struct VmVolumeRequirement {
    pub volume_id: Uuid,
    pub label: String,
    pub role: VmDiskRole,
    pub capacity_gb: DecimalValue,
    pub iops: u64,
    pub throughput_mbps: DecimalValue,
}

#[derive(Clone, Debug)]
pub struct VmTargetSelectionRequest<'a> {
    pub azure_region: &'a str,
    pub source_class: SourceClass,
    pub minimum_vcpu: u32,
    pub minimum_memory_gb: DecimalValue,
    /// True only when the user confirmed the source instance store is used.
    pub requires_local_temp_disk: bool,
    pub minimum_local_temp_disk_gb: DecimalValue,
    pub volumes: &'a [VmVolumeRequirement],
    pub requested_target_arm_sku: Option<&'a str>,
    pub price_availability: Option<&'a VmPriceAvailability>,
}

#[derive(Clone, Debug, Default)]
pub struct VmPriceAvailability {
    pub vm_hourly_rates: BTreeMap<String, DecimalValue>,
    pub managed_disk_dimensions: BTreeSet<VmDiskPriceKey>,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct VmDiskPriceKey {
    pub offer_key: String,
    pub tier_key: Option<String>,
    pub dimension: VmDiskPriceDimension,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum VmDiskPriceDimension {
    CapacityTier,
    CapacityGb,
    AdditionalIops,
    AdditionalThroughput,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct VmTargetSelection {
    pub mapping_status: MappingStatus,
    #[serde(default)]
    pub recommendation_status: VmRecommendationStatus,
    pub requested_lineage: VmLineage,
    pub selected: Option<SelectedVmTarget>,
    pub candidates: Vec<VmCandidateEvaluation>,
    pub outcome_reasons: Vec<VmSelectionReason>,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum VmRecommendationStatus {
    #[default]
    Recommended,
    CapacityFitReviewRequired,
    Incomplete,
    NoEligibleTarget,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct SelectedVmTarget {
    pub arm_sku_name: String,
    pub display_family: String,
    pub lineage: VmLineage,
    pub generation: String,
    pub generation_rank: u32,
    pub lifecycle: VmLifecycle,
    pub azure_region: String,
    pub vcpus: u32,
    pub memory_gb: DecimalValue,
    pub max_data_disk_count: u32,
    pub uncached_disk_iops: u64,
    pub uncached_disk_throughput_mbps: u64,
    pub local_temp_disk_gb: Option<DecimalValue>,
    pub disks: Vec<SelectedManagedDisk>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct SelectedManagedDisk {
    pub volume_id: Uuid,
    pub label: String,
    pub role: VmDiskRole,
    pub offer_key: String,
    pub display_name: String,
    /// Present only for a tiered offer such as Premium SSD.
    pub tier_key: Option<String>,
    pub capacity_gb: DecimalValue,
    pub provisioned_iops: u64,
    pub provisioned_throughput_mbps: DecimalValue,
    /// IOPS above the offer's included baseline, which is what the additional-IOPS meter bills.
    pub billed_additional_iops: u64,
    /// Throughput above the offer's included baseline, in MB/s.
    pub billed_additional_throughput_mbps: DecimalValue,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct VmCandidateEvaluation {
    pub arm_sku_name: String,
    pub vcpus: u32,
    pub memory_gb: DecimalValue,
    pub eligible: bool,
    pub rejection_reasons: Vec<VmSelectionReason>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct VmSelectionReason {
    pub code: VmSelectionReasonCode,
    pub detail: String,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum VmSelectionReasonCode {
    RegionUnavailable,
    LineageMismatch,
    LifecycleIneligible,
    WindowsUnsupported,
    ArchitectureUnsupported,
    PremiumIoUnsupported,
    InsufficientVcpu,
    InsufficientMemory,
    InsufficientLocalTempDisk,
    DataDiskCountExceeded,
    NoEligibleDiskOffer,
    AggregateDiskIopsExceeded,
    AggregateDiskThroughputExceeded,
    TargetOverrideIneligible,
    BurstPolicyReviewRequired,
    InstanceStoreReviewRequired,
    EphemeralDataLossIncompatible,
    HighFrequencyReviewRequired,
    VolumeRoleUnconfirmed,
    PriceUnavailable,
}

#[derive(Clone, Copy, Debug, Error, Eq, PartialEq)]
pub enum VmTargetSelectionError {
    #[error("source vCPU must be greater than zero")]
    InvalidSourceVcpu,
    #[error("source memory must be greater than zero")]
    InvalidSourceMemory,
    #[error("a virtual machine requires at least one persistent volume")]
    NoVolumes,
    #[error("a virtual machine requires exactly one operating system volume")]
    OsVolumeCount,
}

struct EvaluatedCandidate<'a> {
    candidate: &'a VmSizeCandidate,
    disks: Vec<SelectedManagedDisk>,
    hourly_rate: Option<DecimalValue>,
}

/// Selects one Azure VM size and one managed disk per persistent source volume.
///
/// Ranking follows section 8.4: lifecycle, then reviewed generation rank, then vCPU surplus, then
/// memory surplus, aggregate disk-capability surplus, complete pay-as-you-go VM price, and finally
/// the ARM SKU name.
pub fn select_vm_target(
    vm_catalog: &VmCapabilityCatalog,
    disk_catalog: &ManagedDiskCatalog,
    request: &VmTargetSelectionRequest<'_>,
) -> Result<VmTargetSelection, VmTargetSelectionError> {
    validate_request(request)?;

    let requested_lineage = request.source_class.target_lineage();
    let mut evaluations = Vec::new();
    let mut eligible = Vec::new();

    for candidate in &vm_catalog.candidates {
        let mut rejection_reasons = Vec::new();
        let mut disks = Vec::new();

        if !candidate
            .azure_region
            .eq_ignore_ascii_case(request.azure_region)
        {
            // A candidate from another region is not a rejection worth reporting to the user.
            continue;
        }
        if candidate.lineage != requested_lineage {
            if request
                .requested_target_arm_sku
                .is_some_and(|requested| candidate.arm_sku_name.eq_ignore_ascii_case(requested))
            {
                evaluations.push(VmCandidateEvaluation {
                    arm_sku_name: candidate.arm_sku_name.clone(),
                    vcpus: candidate.vcpus,
                    memory_gb: candidate.memory_gb,
                    eligible: false,
                    rejection_reasons: vec![reason(
                        VmSelectionReasonCode::LineageMismatch,
                        format!(
                            "{} is not in the required {requested_lineage:?} lineage.",
                            candidate.arm_sku_name
                        ),
                    )],
                });
            }
            continue;
        }
        if candidate.lifecycle != VmLifecycle::Current {
            rejection_reasons.push(reason(
                VmSelectionReasonCode::LifecycleIneligible,
                format!("{} is not a current generation.", candidate.arm_sku_name),
            ));
        }
        if !candidate.windows_eligible {
            rejection_reasons.push(reason(
                VmSelectionReasonCode::WindowsUnsupported,
                format!("{} is not Windows eligible.", candidate.arm_sku_name),
            ));
        }
        if !candidate.cpu_architecture.eq_ignore_ascii_case("x64") {
            rejection_reasons.push(reason(
                VmSelectionReasonCode::ArchitectureUnsupported,
                format!(
                    "{} reports architecture {}.",
                    candidate.arm_sku_name, candidate.cpu_architecture
                ),
            ));
        }
        if !candidate.premium_io {
            rejection_reasons.push(reason(
                VmSelectionReasonCode::PremiumIoUnsupported,
                format!("{} does not support Premium I/O.", candidate.arm_sku_name),
            ));
        }
        if candidate.vcpus < request.minimum_vcpu {
            rejection_reasons.push(reason(
                VmSelectionReasonCode::InsufficientVcpu,
                format!(
                    "{} provides {} vCPU against {} required.",
                    candidate.arm_sku_name, candidate.vcpus, request.minimum_vcpu
                ),
            ));
        }
        if candidate.memory_gb.0 < request.minimum_memory_gb.0 {
            rejection_reasons.push(reason(
                VmSelectionReasonCode::InsufficientMemory,
                format!(
                    "{} provides {} GiB against {} GiB required.",
                    candidate.arm_sku_name, candidate.memory_gb, request.minimum_memory_gb
                ),
            ));
        }
        if request.requires_local_temp_disk {
            let local = candidate.local_temp_disk_gb.unwrap_or(DecimalValue::ZERO);
            if local.0 < request.minimum_local_temp_disk_gb.0 {
                rejection_reasons.push(reason(
                    VmSelectionReasonCode::InsufficientLocalTempDisk,
                    format!(
                        "{} provides {} GiB of local temporary storage against {} GiB required.",
                        candidate.arm_sku_name, local, request.minimum_local_temp_disk_gb
                    ),
                ));
            }
        }

        let data_disk_count = request
            .volumes
            .iter()
            .filter(|volume| volume.role == VmDiskRole::Data)
            .count();
        if data_disk_count > candidate.max_data_disk_count as usize {
            rejection_reasons.push(reason(
                VmSelectionReasonCode::DataDiskCountExceeded,
                format!(
                    "{} supports {} data disks against {} required.",
                    candidate.arm_sku_name, candidate.max_data_disk_count, data_disk_count
                ),
            ));
        }

        for volume in request.volumes {
            match select_disk(disk_catalog, request.azure_region, volume) {
                Some(disk) => disks.push(disk),
                None => rejection_reasons.push(reason(
                    VmSelectionReasonCode::NoEligibleDiskOffer,
                    format!(
                        "No managed disk offer in {} satisfies volume {} at {} GiB, {} IOPS, and {} MB/s.",
                        request.azure_region,
                        volume.label,
                        volume.capacity_gb,
                        volume.iops,
                        volume.throughput_mbps
                    ),
                )),
            }
        }

        if disks.len() == request.volumes.len() {
            let aggregate_iops: u64 = disks.iter().map(|disk| disk.provisioned_iops).sum();
            let aggregate_throughput: Decimal = disks
                .iter()
                .map(|disk| disk.provisioned_throughput_mbps.0)
                .sum();
            if aggregate_iops > candidate.uncached_disk_iops {
                rejection_reasons.push(reason(
                    VmSelectionReasonCode::AggregateDiskIopsExceeded,
                    format!(
                        "{} allows {} uncached disk IOPS against {} required.",
                        candidate.arm_sku_name, candidate.uncached_disk_iops, aggregate_iops
                    ),
                ));
            }
            if aggregate_throughput > Decimal::from(candidate.uncached_disk_throughput_mbps) {
                rejection_reasons.push(reason(
                    VmSelectionReasonCode::AggregateDiskThroughputExceeded,
                    format!(
                        "{} allows {} MB/s of uncached disk throughput against {} MB/s required.",
                        candidate.arm_sku_name,
                        candidate.uncached_disk_throughput_mbps,
                        aggregate_throughput
                    ),
                ));
            }
        }

        let hourly_rate = request.price_availability.and_then(|availability| {
            availability
                .vm_hourly_rates
                .get(&candidate.arm_sku_name.to_ascii_lowercase())
                .copied()
        });
        if request.price_availability.is_some() && hourly_rate.is_none() {
            rejection_reasons.push(reason(
                VmSelectionReasonCode::PriceUnavailable,
                format!(
                    "{} does not have a complete Windows PAYG rate in the coherent target snapshot.",
                    candidate.arm_sku_name
                ),
            ));
        }
        if let Some(availability) = request.price_availability {
            for disk in &disks {
                if !managed_disk_price_is_complete(availability, disk) {
                    rejection_reasons.push(reason(
                        VmSelectionReasonCode::PriceUnavailable,
                        format!(
                            "Managed disk {} for volume {} is missing a required coherent price dimension.",
                            disk.tier_key.as_deref().unwrap_or(&disk.offer_key),
                            disk.label
                        ),
                    ));
                }
            }
        }

        evaluations.push(VmCandidateEvaluation {
            arm_sku_name: candidate.arm_sku_name.clone(),
            vcpus: candidate.vcpus,
            memory_gb: candidate.memory_gb,
            eligible: rejection_reasons.is_empty(),
            rejection_reasons,
        });

        if evaluations
            .last()
            .is_some_and(|evaluation| evaluation.eligible)
        {
            eligible.push(EvaluatedCandidate {
                candidate,
                disks,
                hourly_rate,
            });
        }
    }

    evaluations.sort_by(|left, right| left.arm_sku_name.cmp(&right.arm_sku_name));

    let best = match request.requested_target_arm_sku {
        Some(requested) => eligible.into_iter().find(|evaluated| {
            evaluated
                .candidate
                .arm_sku_name
                .eq_ignore_ascii_case(requested)
        }),
        None => eligible.into_iter().min_by(|left, right| rank(left, right)),
    };
    let Some(best) = best else {
        let outcome_reasons = match request.requested_target_arm_sku {
            Some(requested) => vec![reason(
                VmSelectionReasonCode::TargetOverrideIneligible,
                format!(
                    "Requested target {requested} is absent or fails the reviewed region, lineage, lifecycle, compute, local-storage, or managed-disk requirements."
                ),
            )],
            None => vec![reason(
                VmSelectionReasonCode::LineageMismatch,
                format!(
                    "No current {requested_lineage:?} size in {} satisfies the vCPU, memory, disk, and aggregate limits.",
                    request.azure_region
                ),
            )],
        };
        return Ok(VmTargetSelection {
            mapping_status: MappingStatus::NoMapping,
            recommendation_status: VmRecommendationStatus::NoEligibleTarget,
            requested_lineage,
            selected: None,
            candidates: evaluations,
            outcome_reasons,
        });
    };

    let candidate = best.candidate;
    Ok(VmTargetSelection {
        mapping_status: MappingStatus::Mapped,
        recommendation_status: VmRecommendationStatus::Recommended,
        requested_lineage,
        selected: Some(SelectedVmTarget {
            arm_sku_name: candidate.arm_sku_name.clone(),
            display_family: candidate.display_family.clone(),
            lineage: candidate.lineage,
            generation: candidate.generation.clone(),
            generation_rank: candidate.generation_rank,
            lifecycle: candidate.lifecycle,
            azure_region: candidate.azure_region.clone(),
            vcpus: candidate.vcpus,
            memory_gb: candidate.memory_gb,
            max_data_disk_count: candidate.max_data_disk_count,
            uncached_disk_iops: candidate.uncached_disk_iops,
            uncached_disk_throughput_mbps: candidate.uncached_disk_throughput_mbps,
            local_temp_disk_gb: candidate.local_temp_disk_gb,
            disks: best.disks,
        }),
        candidates: evaluations,
        outcome_reasons: Vec::new(),
    })
}

fn validate_request(request: &VmTargetSelectionRequest<'_>) -> Result<(), VmTargetSelectionError> {
    if request.minimum_vcpu == 0 {
        return Err(VmTargetSelectionError::InvalidSourceVcpu);
    }
    if request.minimum_memory_gb.0 <= Decimal::ZERO {
        return Err(VmTargetSelectionError::InvalidSourceMemory);
    }
    if request.volumes.is_empty() {
        return Err(VmTargetSelectionError::NoVolumes);
    }
    if request
        .volumes
        .iter()
        .filter(|volume| volume.role == VmDiskRole::Os)
        .count()
        != 1
    {
        return Err(VmTargetSelectionError::OsVolumeCount);
    }
    Ok(())
}

/// Chooses the smallest capability-fit disk for one volume.
///
/// Preference order: smallest provisioned capacity, then an offer whose performance is provisioned
/// independently, then the offer key. Independent provisioning wins a capacity tie because it
/// preserves the source IOPS and throughput exactly instead of over-provisioning to a fixed tier.
fn select_disk(
    catalog: &ManagedDiskCatalog,
    azure_region: &str,
    volume: &VmVolumeRequirement,
) -> Option<SelectedManagedDisk> {
    let mut best: Option<SelectedManagedDisk> = None;

    for offer in &catalog.offers {
        if !offer
            .azure_regions
            .iter()
            .any(|region| region.eq_ignore_ascii_case(azure_region))
        {
            continue;
        }
        if !offer.allowed_roles.contains(&volume.role) {
            continue;
        }
        if volume.iops > offer.maximum_iops {
            continue;
        }
        if volume.throughput_mbps.0 > Decimal::from(offer.maximum_throughput_mbps) {
            continue;
        }

        let disk = if offer.performance_is_provisioned_independently {
            independent_disk(offer, volume)
        } else {
            tiered_disk(offer, volume)
        };

        let Some(disk) = disk else { continue };
        best = Some(match best {
            None => disk,
            Some(current) => {
                if prefer_disk(&disk, &current, catalog) {
                    disk
                } else {
                    current
                }
            }
        });
    }

    best
}

fn independent_disk(
    offer: &ManagedDiskOffer,
    volume: &VmVolumeRequirement,
) -> Option<SelectedManagedDisk> {
    let minimum = offer.minimum_capacity_gb.unwrap_or(DecimalValue::ZERO);
    let increment = offer
        .capacity_increment_gb
        .filter(|increment| increment.0 > Decimal::ZERO)?;

    let mut capacity = volume.capacity_gb.0.max(minimum.0);
    let remainder = capacity % increment.0;
    if remainder > Decimal::ZERO {
        capacity += increment.0 - remainder;
    }
    if capacity > offer.maximum_capacity_gb.0 {
        return None;
    }

    let included_iops = offer.included_iops.unwrap_or(0);
    let included_throughput = offer.included_throughput_mbps.unwrap_or(DecimalValue::ZERO);
    let provisioned_iops = volume.iops.max(included_iops);
    let provisioned_throughput = volume.throughput_mbps.0.max(included_throughput.0);

    Some(SelectedManagedDisk {
        volume_id: volume.volume_id,
        label: volume.label.clone(),
        role: volume.role,
        offer_key: offer.offer_key.clone(),
        display_name: offer.display_name.clone(),
        tier_key: None,
        capacity_gb: DecimalValue(capacity),
        provisioned_iops,
        provisioned_throughput_mbps: DecimalValue(provisioned_throughput),
        billed_additional_iops: provisioned_iops.saturating_sub(included_iops),
        billed_additional_throughput_mbps: DecimalValue(
            (provisioned_throughput - included_throughput.0).max(Decimal::ZERO),
        ),
    })
}

fn tiered_disk(
    offer: &ManagedDiskOffer,
    volume: &VmVolumeRequirement,
) -> Option<SelectedManagedDisk> {
    let tier = offer
        .tiers
        .iter()
        .filter(|tier| {
            tier.capacity_gb.0 >= volume.capacity_gb.0
                && tier.provisioned_iops >= volume.iops
                && tier.provisioned_throughput_mbps.0 >= volume.throughput_mbps.0
        })
        .min_by(|left, right| {
            left.capacity_gb
                .0
                .cmp(&right.capacity_gb.0)
                .then_with(|| left.tier_key.cmp(&right.tier_key))
        })?;

    Some(SelectedManagedDisk {
        volume_id: volume.volume_id,
        label: volume.label.clone(),
        role: volume.role,
        offer_key: offer.offer_key.clone(),
        display_name: offer.display_name.clone(),
        tier_key: Some(tier.tier_key.clone()),
        capacity_gb: tier.capacity_gb,
        provisioned_iops: tier.provisioned_iops,
        provisioned_throughput_mbps: tier.provisioned_throughput_mbps,
        billed_additional_iops: 0,
        billed_additional_throughput_mbps: DecimalValue::ZERO,
    })
}

fn prefer_disk(
    candidate: &SelectedManagedDisk,
    current: &SelectedManagedDisk,
    catalog: &ManagedDiskCatalog,
) -> bool {
    let independent = |disk: &SelectedManagedDisk| {
        catalog
            .offers
            .iter()
            .find(|offer| offer.offer_key == disk.offer_key)
            .is_some_and(|offer| offer.performance_is_provisioned_independently)
    };

    match candidate.capacity_gb.0.cmp(&current.capacity_gb.0) {
        Ordering::Less => true,
        Ordering::Greater => false,
        Ordering::Equal => match independent(candidate).cmp(&independent(current)) {
            Ordering::Greater => true,
            Ordering::Less => false,
            Ordering::Equal => candidate.offer_key < current.offer_key,
        },
    }
}

fn rank(left: &EvaluatedCandidate<'_>, right: &EvaluatedCandidate<'_>) -> Ordering {
    // Current lifecycle first, then the newest reviewed generation, then the smallest surplus.
    let lifecycle = |candidate: &VmSizeCandidate| match candidate.lifecycle {
        VmLifecycle::Current => 0_u8,
        VmLifecycle::Previous => 1,
    };

    lifecycle(left.candidate)
        .cmp(&lifecycle(right.candidate))
        .then_with(|| {
            right
                .candidate
                .generation_rank
                .cmp(&left.candidate.generation_rank)
        })
        .then_with(|| left.candidate.vcpus.cmp(&right.candidate.vcpus))
        .then_with(|| left.candidate.memory_gb.0.cmp(&right.candidate.memory_gb.0))
        .then_with(|| {
            disk_capacity(left)
                .cmp(&disk_capacity(right))
                .then_with(|| left.hourly_rate.cmp(&right.hourly_rate))
                .then_with(|| {
                    left.candidate
                        .arm_sku_name
                        .cmp(&right.candidate.arm_sku_name)
                })
        })
}

fn managed_disk_price_is_complete(
    availability: &VmPriceAvailability,
    disk: &SelectedManagedDisk,
) -> bool {
    let contains = |dimension| {
        availability
            .managed_disk_dimensions
            .contains(&VmDiskPriceKey {
                offer_key: disk.offer_key.clone(),
                tier_key: disk.tier_key.clone(),
                dimension,
            })
    };
    if disk.tier_key.is_some() {
        return contains(VmDiskPriceDimension::CapacityTier);
    }
    contains(VmDiskPriceDimension::CapacityGb)
        && (disk.billed_additional_iops == 0 || contains(VmDiskPriceDimension::AdditionalIops))
        && (disk.billed_additional_throughput_mbps.0 == Decimal::ZERO
            || contains(VmDiskPriceDimension::AdditionalThroughput))
}

fn disk_capacity(candidate: &EvaluatedCandidate<'_>) -> Decimal {
    candidate
        .disks
        .iter()
        .map(|disk| disk.capacity_gb.0)
        .sum::<Decimal>()
}

fn reason(code: VmSelectionReasonCode, detail: String) -> VmSelectionReason {
    VmSelectionReason { code, detail }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn vm_catalog() -> VmCapabilityCatalog {
        serde_json::from_str(include_str!(
            "../../../app/catalogs/azure-vm-capabilities.json"
        ))
        .expect("the shipped virtual machine capability catalog parses")
    }

    fn disk_catalog() -> ManagedDiskCatalog {
        serde_json::from_str(include_str!(
            "../../../app/catalogs/azure-managed-disk-capabilities.json"
        ))
        .expect("the shipped managed disk capability catalog parses")
    }

    fn decimal(value: i64) -> DecimalValue {
        DecimalValue(Decimal::from(value))
    }

    /// A deliberately small operating system volume so that lineage tests are not rejected by the
    /// aggregate disk limits of the smallest burstable sizes.
    fn os_volume() -> VmVolumeRequirement {
        VmVolumeRequirement {
            volume_id: Uuid::from_u128(1),
            label: "C:".to_owned(),
            role: VmDiskRole::Os,
            capacity_gb: decimal(32),
            iops: 120,
            throughput_mbps: decimal(25),
        }
    }

    fn request<'a>(
        source_class: SourceClass,
        minimum_vcpu: u32,
        minimum_memory_gb: i64,
        volumes: &'a [VmVolumeRequirement],
    ) -> VmTargetSelectionRequest<'a> {
        VmTargetSelectionRequest {
            azure_region: "swedencentral",
            source_class,
            minimum_vcpu,
            minimum_memory_gb: decimal(minimum_memory_gb),
            requires_local_temp_disk: false,
            minimum_local_temp_disk_gb: DecimalValue::ZERO,
            volumes,
            requested_target_arm_sku: None,
            price_availability: None,
        }
    }

    fn select(request: &VmTargetSelectionRequest<'_>) -> VmTargetSelection {
        select_vm_target(&vm_catalog(), &disk_catalog(), request).expect("the request is valid")
    }

    fn selected_sku(
        source_class: SourceClass,
        minimum_vcpu: u32,
        minimum_memory_gb: i64,
        volumes: &[VmVolumeRequirement],
    ) -> String {
        let selection = select(&request(
            source_class,
            minimum_vcpu,
            minimum_memory_gb,
            volumes,
        ));
        assert_eq!(selection.mapping_status, MappingStatus::Mapped);
        selection
            .selected
            .expect("a mapped selection carries a target")
            .arm_sku_name
    }

    #[test]
    fn reviewed_source_families_classify_and_unlisted_families_do_not() {
        assert_eq!(
            classify_source_instance("t3.large"),
            Some(SourceClass::Burstable)
        );
        assert_eq!(
            classify_source_instance("m6i.large"),
            Some(SourceClass::GeneralPurpose)
        );
        assert_eq!(
            classify_source_instance("r6id.8xlarge"),
            Some(SourceClass::MemoryOptimized)
        );
        assert_eq!(
            classify_source_instance("z1d.2xlarge"),
            Some(SourceClass::HighFrequencyMemoryOptimized)
        );
        // An unlisted family has no recommended mapping rather than a guessed one.
        assert_eq!(classify_source_instance("x2iedn.xlarge"), None);
        assert_eq!(classify_source_instance("p5.48xlarge"), None);
        assert_eq!(classify_source_instance(""), None);
    }

    #[test]
    fn shipped_catalogs_parse_and_carry_only_reviewed_eligible_records() {
        let vms = vm_catalog();
        assert_eq!(vms.schema_version, "1.0.0");
        assert!(!vms.candidates.is_empty());
        assert!(vms.candidates.iter().all(|candidate| {
            candidate.lifecycle == VmLifecycle::Current
                && candidate.windows_eligible
                && candidate.premium_io
                && candidate.cpu_architecture == "x64"
                && candidate.vcpus > 0
        }));

        let disks = disk_catalog();
        assert_eq!(disks.schema_version, "1.0.0");
        // Premium SSD v2 provisions performance independently and is data-only.
        let v2 = disks
            .offers
            .iter()
            .find(|offer| offer.offer_key == "premium_ssd_v2_lrs")
            .expect("the catalog offers Premium SSD v2");
        assert!(v2.performance_is_provisioned_independently);
        assert_eq!(v2.allowed_roles, vec![VmDiskRole::Data]);
        assert!(
            disks
                .offers
                .iter()
                .any(|offer| offer.allowed_roles.contains(&VmDiskRole::Os))
        );
    }

    #[test]
    fn section_3_2_source_shapes_map_to_the_newest_eligible_current_size() {
        let volumes = [os_volume()];
        assert_eq!(
            selected_sku(SourceClass::Burstable, 2, 8, &volumes),
            "Standard_B2s_v2"
        );
        assert_eq!(
            selected_sku(SourceClass::Burstable, 4, 16, &volumes),
            "Standard_B4s_v2"
        );
        assert_eq!(
            selected_sku(SourceClass::GeneralPurpose, 2, 8, &volumes),
            "Standard_D2ds_v7"
        );
        assert_eq!(
            selected_sku(SourceClass::MemoryOptimized, 2, 16, &volumes),
            "Standard_E2ds_v7"
        );
        assert_eq!(
            selected_sku(SourceClass::MemoryOptimized, 32, 256, &volumes),
            "Standard_E32ds_v7"
        );
        assert_eq!(
            selected_sku(SourceClass::MemoryOptimized, 48, 384, &volumes),
            "Standard_E48ds_v7"
        );
        assert_eq!(
            selected_sku(SourceClass::HighFrequencyMemoryOptimized, 8, 64, &volumes),
            "Standard_E8ds_v7"
        );
    }

    #[test]
    fn burstable_and_high_frequency_sources_keep_their_required_caveats() {
        assert!(SourceClass::Burstable.required_caveat().is_some());
        assert!(
            SourceClass::HighFrequencyMemoryOptimized
                .required_caveat()
                .is_some()
        );
        assert!(SourceClass::GeneralPurpose.required_caveat().is_none());
        assert!(SourceClass::MemoryOptimized.required_caveat().is_none());
        assert_eq!(
            SourceClass::HighFrequencyMemoryOptimized.target_lineage(),
            VmLineage::MemoryOptimized
        );
    }

    #[test]
    fn an_operating_system_volume_takes_the_smallest_fitting_tier_and_never_premium_ssd_v2() {
        let volumes = [os_volume()];
        let selection = select(&request(SourceClass::GeneralPurpose, 2, 8, &volumes));
        let target = selection.selected.expect("a target is selected");
        let os = target
            .disks
            .iter()
            .find(|disk| disk.role == VmDiskRole::Os)
            .expect("the operating system volume is mapped");
        assert_eq!(os.offer_key, "premium_ssd_lrs");
        assert_eq!(os.tier_key.as_deref(), Some("P4"));
        assert_eq!(os.capacity_gb, decimal(32));
        assert_eq!(os.billed_additional_iops, 0);
        assert_eq!(os.billed_additional_throughput_mbps, DecimalValue::ZERO);
    }

    #[test]
    fn every_persistent_volume_maps_to_its_own_disk_billing_only_additional_performance() {
        let volumes = [
            os_volume(),
            VmVolumeRequirement {
                volume_id: Uuid::from_u128(2),
                label: "D:".to_owned(),
                role: VmDiskRole::Data,
                capacity_gb: decimal(512),
                iops: 8_000,
                throughput_mbps: decimal(300),
            },
        ];
        let selection = select(&request(SourceClass::MemoryOptimized, 32, 256, &volumes));
        let target = selection.selected.expect("a target is selected");
        assert_eq!(target.disks.len(), volumes.len());

        let data = target
            .disks
            .iter()
            .find(|disk| disk.role == VmDiskRole::Data)
            .expect("the data volume is mapped");
        // Premium SSD v2 fits the source capacity exactly instead of over-provisioning to P60.
        assert_eq!(data.offer_key, "premium_ssd_v2_lrs");
        assert_eq!(data.tier_key, None);
        assert_eq!(data.capacity_gb, decimal(512));
        assert_eq!(data.provisioned_iops, 8_000);
        assert_eq!(data.provisioned_throughput_mbps, decimal(300));
        assert_eq!(data.billed_additional_iops, 5_000);
        assert_eq!(data.billed_additional_throughput_mbps, decimal(175));
    }

    #[test]
    fn requiring_local_temporary_storage_reports_no_mapping_rather_than_a_guess() {
        let volumes = [os_volume()];
        let mut requires_local = request(SourceClass::MemoryOptimized, 32, 256, &volumes);
        requires_local.requires_local_temp_disk = true;
        requires_local.minimum_local_temp_disk_gb = decimal(1_900);

        let selection = select(&requires_local);
        assert_eq!(selection.mapping_status, MappingStatus::NoMapping);
        assert!(selection.selected.is_none());
        assert!(selection.candidates.iter().any(|candidate| {
            candidate
                .rejection_reasons
                .iter()
                .any(|reason| reason.code == VmSelectionReasonCode::InsufficientLocalTempDisk)
        }));
    }

    #[test]
    fn an_unreviewed_region_reports_no_mapping_rather_than_a_guess() {
        let volumes = [os_volume()];
        let mut unreviewed = request(SourceClass::GeneralPurpose, 2, 8, &volumes);
        unreviewed.azure_region = "westeurope";

        let selection = select(&unreviewed);
        assert_eq!(selection.mapping_status, MappingStatus::NoMapping);
        assert!(selection.selected.is_none());
        assert!(selection.candidates.is_empty());
    }

    #[test]
    fn an_eligible_target_override_is_revalidated_and_selected() {
        let volumes = [os_volume()];
        let mut overridden = request(SourceClass::GeneralPurpose, 2, 8, &volumes);
        overridden.requested_target_arm_sku = Some("Standard_D4s_v7");

        let selection = select(&overridden);
        assert_eq!(selection.mapping_status, MappingStatus::Mapped);
        assert_eq!(
            selection
                .selected
                .expect("the eligible override is selected")
                .arm_sku_name,
            "Standard_D4s_v7"
        );
    }

    #[test]
    fn a_target_override_cannot_bypass_lineage_validation() {
        let volumes = [os_volume()];
        let mut overridden = request(SourceClass::GeneralPurpose, 2, 8, &volumes);
        overridden.requested_target_arm_sku = Some("Standard_B2s_v2");

        let selection = select(&overridden);
        assert_eq!(selection.mapping_status, MappingStatus::NoMapping);
        assert_eq!(
            selection.recommendation_status,
            VmRecommendationStatus::NoEligibleTarget
        );
        assert!(
            selection
                .outcome_reasons
                .iter()
                .any(|reason| { reason.code == VmSelectionReasonCode::TargetOverrideIneligible })
        );
        assert!(selection.candidates.iter().any(|candidate| {
            candidate.arm_sku_name == "Standard_B2s_v2"
                && candidate
                    .rejection_reasons
                    .iter()
                    .any(|reason| reason.code == VmSelectionReasonCode::LineageMismatch)
        }));
    }

    #[test]
    fn an_unpriced_capability_candidate_is_rejected_for_a_priced_fallback() {
        let volumes = [os_volume()];
        let mut priced = request(SourceClass::GeneralPurpose, 2, 8, &volumes);
        let availability = price_availability(&[("Standard_D2s_v7", 1)], true);
        priced.price_availability = Some(&availability);

        let selection = select(&priced);
        assert_eq!(
            selection
                .selected
                .expect("a complete priced fallback is selected")
                .arm_sku_name,
            "Standard_D2s_v7"
        );
        assert!(selection.candidates.iter().any(|candidate| {
            candidate.arm_sku_name == "Standard_D2ds_v7"
                && candidate
                    .rejection_reasons
                    .iter()
                    .any(|reason| reason.code == VmSelectionReasonCode::PriceUnavailable)
        }));
    }

    #[test]
    fn a_missing_managed_disk_dimension_fails_closed() {
        let volumes = [os_volume()];
        let mut priced = request(SourceClass::GeneralPurpose, 2, 8, &volumes);
        let availability = price_availability(&[("Standard_D2ds_v7", 1)], false);
        priced.price_availability = Some(&availability);

        let selection = select(&priced);
        assert_eq!(selection.mapping_status, MappingStatus::NoMapping);
        assert!(selection.candidates.iter().any(|candidate| {
            candidate.arm_sku_name == "Standard_D2ds_v7"
                && candidate
                    .rejection_reasons
                    .iter()
                    .any(|reason| reason.code == VmSelectionReasonCode::PriceUnavailable)
        }));
    }

    #[test]
    fn complete_payg_price_breaks_an_otherwise_equal_capability_tie() {
        let volumes = [os_volume()];
        let mut priced = request(SourceClass::GeneralPurpose, 2, 8, &volumes);
        let availability =
            price_availability(&[("Standard_D2ds_v7", 2), ("Standard_D2s_v7", 1)], true);
        priced.price_availability = Some(&availability);

        let selection = select(&priced);
        assert_eq!(
            selection
                .selected
                .expect("the lower complete rate wins the final price tie-breaker")
                .arm_sku_name,
            "Standard_D2s_v7"
        );
    }

    #[test]
    fn a_source_larger_than_every_reviewed_size_reports_no_mapping() {
        let volumes = [os_volume()];
        let selection = select(&request(SourceClass::Burstable, 64, 256, &volumes));
        assert_eq!(selection.mapping_status, MappingStatus::NoMapping);
        assert!(selection.candidates.iter().any(|candidate| {
            candidate
                .rejection_reasons
                .iter()
                .any(|reason| reason.code == VmSelectionReasonCode::InsufficientVcpu)
        }));
    }

    #[test]
    fn request_validation_rejects_unusable_shapes() {
        let volumes = [os_volume()];
        let vms = vm_catalog();
        let disks = disk_catalog();
        let error = |request: VmTargetSelectionRequest<'_>| {
            select_vm_target(&vms, &disks, &request).expect_err("the request is rejected")
        };

        let mut zero_vcpu = request(SourceClass::GeneralPurpose, 2, 8, &volumes);
        zero_vcpu.minimum_vcpu = 0;
        assert_eq!(error(zero_vcpu), VmTargetSelectionError::InvalidSourceVcpu);

        let mut zero_memory = request(SourceClass::GeneralPurpose, 2, 8, &volumes);
        zero_memory.minimum_memory_gb = DecimalValue::ZERO;
        assert_eq!(
            error(zero_memory),
            VmTargetSelectionError::InvalidSourceMemory
        );

        assert_eq!(
            error(request(SourceClass::GeneralPurpose, 2, 8, &[])),
            VmTargetSelectionError::NoVolumes
        );

        let two_operating_systems = [os_volume(), os_volume()];
        assert_eq!(
            error(request(
                SourceClass::GeneralPurpose,
                2,
                8,
                &two_operating_systems
            )),
            VmTargetSelectionError::OsVolumeCount
        );
    }

    #[test]
    fn selection_is_deterministic_for_an_identical_request() {
        let volumes = [os_volume()];
        let first = select(&request(SourceClass::MemoryOptimized, 8, 64, &volumes));
        let second = select(&request(SourceClass::MemoryOptimized, 8, 64, &volumes));
        assert_eq!(first, second);
    }

    fn price_availability(vm_rates: &[(&str, i64)], include_p4: bool) -> VmPriceAvailability {
        VmPriceAvailability {
            vm_hourly_rates: vm_rates
                .iter()
                .map(|(sku, rate)| (sku.to_ascii_lowercase(), decimal(*rate)))
                .collect(),
            managed_disk_dimensions: if include_p4 {
                BTreeSet::from([VmDiskPriceKey {
                    offer_key: "premium_ssd_lrs".to_owned(),
                    tier_key: Some("P4".to_owned()),
                    dimension: VmDiskPriceDimension::CapacityTier,
                }])
            } else {
                BTreeSet::new()
            },
        }
    }
}
