<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="Microsoft.Identity.Client.Broker" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyMetadata Include="CalculatorApiOrigin" Value="$(CalculatorApiOrigin)" />
    <AssemblyMetadata Include="CalculatorCompanionClientId" Value="$(CalculatorCompanionClientId)" />
    <AssemblyMetadata Include="CalculatorApiScope" Value="$(CalculatorApiScope)" />
  </ItemGroup>

</Project>
